<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    // //斐波拉契数列
    // //方法1
    // let arr = [1,1]
    // let length = 100//length为想要构造数列的长度
    // for(let i=2;i<length;i++){
    //     arr[i] = arr[i-1] + arr[i-2]
    // }
    // //方法2
    // let arr1 = Fibonacci2(100)//得到某个确定的斐波拉契数
    // function Fibonacci2 (n , ac1 = 1 , ac2 = 1) {
    //   if( n <= 1 ) {return ac2};
    //   return Fibonacci2 (n - 1, ac2, ac1 + ac2);
    // }
    // console.log(arr);
    // console.log(arr1);
    //Promise.all实现
    // //Promise
    // let promise1 = new Promise((resolve,reject) => {
    //     axios.get('http://localhost:30001/promiseTest')
    //     //axios.get执行成功时的回调 将结果通过resolve传出去 因为axios返回的也是一个Promise对象，所以可以使用.then
    //     .then((res) => {
    //         resolve(res)
    //     })
    //     .catch((err) => {//axios.get执行失败时的回调
    //         reject(err)
    //     })
    // })
    // promise1.then((res) => {
    //     console.log(res);
    // }).catch((err) => {
    //     console.log(err)
    // })
    //Promise.all
    let p1 = new Promise( resolve => {
        resolve('我是p1成功')
    })
    let p2 = new Promise( (resolve, reject) => {
        resolve('我是p2成功')
        reject('p2失败')
    })
    let myAll = function myall(promises) {
        let values = []//保存成功的promise的返回值 因为有好几个 所以使用数组来保存
        return new Promise((resolve, reject) => {//返回一个Promise对象 使之可以调用then和catch方法
            promises.forEach((promise) => {// 循环调用每一个promise的then方法
                promise.then(
                    (value) => {
                        values.push(value) // 成功则将改方法的返回值存入values中
                        if(values.length === promises.length){ 
                            resolve(values) // 当所有的promise都成功时 返回resolve
                        }
                    },
                    (err) => {
                        reject(err) // 当其中任一promise执行失败时结束执行
                    })
            })
        })
    }
    myAll([p1,p2]).then( res => {
        console.log(res);
    }).catch( err => {
        console.log(err);
    })
</script>
</html>